# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/junyao/git_OTC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/junyao/git_OTC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/junyao/git_OTC/CMakeFiles /home/junyao/git_OTC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/junyao/git_OTC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TMC_OCTv3

# Build rule for target.
TMC_OCTv3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TMC_OCTv3
.PHONY : TMC_OCTv3

# fast build rule for target.
TMC_OCTv3/fast:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/build
.PHONY : TMC_OCTv3/fast

src/tmcoct_bias.o: src/tmcoct_bias.c.o

.PHONY : src/tmcoct_bias.o

# target to build an object file
src/tmcoct_bias.c.o:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_bias.c.o
.PHONY : src/tmcoct_bias.c.o

src/tmcoct_bias.i: src/tmcoct_bias.c.i

.PHONY : src/tmcoct_bias.i

# target to preprocess a source file
src/tmcoct_bias.c.i:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_bias.c.i
.PHONY : src/tmcoct_bias.c.i

src/tmcoct_bias.s: src/tmcoct_bias.c.s

.PHONY : src/tmcoct_bias.s

# target to generate assembly for a file
src/tmcoct_bias.c.s:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_bias.c.s
.PHONY : src/tmcoct_bias.c.s

src/tmcoct_go.o: src/tmcoct_go.c.o

.PHONY : src/tmcoct_go.o

# target to build an object file
src/tmcoct_go.c.o:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_go.c.o
.PHONY : src/tmcoct_go.c.o

src/tmcoct_go.i: src/tmcoct_go.c.i

.PHONY : src/tmcoct_go.i

# target to preprocess a source file
src/tmcoct_go.c.i:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_go.c.i
.PHONY : src/tmcoct_go.c.i

src/tmcoct_go.s: src/tmcoct_go.c.s

.PHONY : src/tmcoct_go.s

# target to generate assembly for a file
src/tmcoct_go.c.s:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_go.c.s
.PHONY : src/tmcoct_go.c.s

src/tmcoct_io.o: src/tmcoct_io.c.o

.PHONY : src/tmcoct_io.o

# target to build an object file
src/tmcoct_io.c.o:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_io.c.o
.PHONY : src/tmcoct_io.c.o

src/tmcoct_io.i: src/tmcoct_io.c.i

.PHONY : src/tmcoct_io.i

# target to preprocess a source file
src/tmcoct_io.c.i:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_io.c.i
.PHONY : src/tmcoct_io.c.i

src/tmcoct_io.s: src/tmcoct_io.c.s

.PHONY : src/tmcoct_io.s

# target to generate assembly for a file
src/tmcoct_io.c.s:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_io.c.s
.PHONY : src/tmcoct_io.c.s

src/tmcoct_main.o: src/tmcoct_main.c.o

.PHONY : src/tmcoct_main.o

# target to build an object file
src/tmcoct_main.c.o:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_main.c.o
.PHONY : src/tmcoct_main.c.o

src/tmcoct_main.i: src/tmcoct_main.c.i

.PHONY : src/tmcoct_main.i

# target to preprocess a source file
src/tmcoct_main.c.i:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_main.c.i
.PHONY : src/tmcoct_main.c.i

src/tmcoct_main.s: src/tmcoct_main.c.s

.PHONY : src/tmcoct_main.s

# target to generate assembly for a file
src/tmcoct_main.c.s:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_main.c.s
.PHONY : src/tmcoct_main.c.s

src/tmcoct_mesh.o: src/tmcoct_mesh.c.o

.PHONY : src/tmcoct_mesh.o

# target to build an object file
src/tmcoct_mesh.c.o:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_mesh.c.o
.PHONY : src/tmcoct_mesh.c.o

src/tmcoct_mesh.i: src/tmcoct_mesh.c.i

.PHONY : src/tmcoct_mesh.i

# target to preprocess a source file
src/tmcoct_mesh.c.i:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_mesh.c.i
.PHONY : src/tmcoct_mesh.c.i

src/tmcoct_mesh.s: src/tmcoct_mesh.c.s

.PHONY : src/tmcoct_mesh.s

# target to generate assembly for a file
src/tmcoct_mesh.c.s:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_mesh.c.s
.PHONY : src/tmcoct_mesh.c.s

src/tmcoct_nr.o: src/tmcoct_nr.c.o

.PHONY : src/tmcoct_nr.o

# target to build an object file
src/tmcoct_nr.c.o:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_nr.c.o
.PHONY : src/tmcoct_nr.c.o

src/tmcoct_nr.i: src/tmcoct_nr.c.i

.PHONY : src/tmcoct_nr.i

# target to preprocess a source file
src/tmcoct_nr.c.i:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_nr.c.i
.PHONY : src/tmcoct_nr.c.i

src/tmcoct_nr.s: src/tmcoct_nr.c.s

.PHONY : src/tmcoct_nr.s

# target to generate assembly for a file
src/tmcoct_nr.c.s:
	$(MAKE) -f CMakeFiles/TMC_OCTv3.dir/build.make CMakeFiles/TMC_OCTv3.dir/src/tmcoct_nr.c.s
.PHONY : src/tmcoct_nr.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TMC_OCTv3"
	@echo "... src/tmcoct_bias.o"
	@echo "... src/tmcoct_bias.i"
	@echo "... src/tmcoct_bias.s"
	@echo "... src/tmcoct_go.o"
	@echo "... src/tmcoct_go.i"
	@echo "... src/tmcoct_go.s"
	@echo "... src/tmcoct_io.o"
	@echo "... src/tmcoct_io.i"
	@echo "... src/tmcoct_io.s"
	@echo "... src/tmcoct_main.o"
	@echo "... src/tmcoct_main.i"
	@echo "... src/tmcoct_main.s"
	@echo "... src/tmcoct_mesh.o"
	@echo "... src/tmcoct_mesh.i"
	@echo "... src/tmcoct_mesh.s"
	@echo "... src/tmcoct_nr.o"
	@echo "... src/tmcoct_nr.i"
	@echo "... src/tmcoct_nr.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

